---
- hosts: all
  sudo: yes
  tasks:   
    - name: Prepare for nodejs installation
      shell: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
    - name: install nodejs
      apt: name=nodejs state=latest update_cache=yes
